spring.application.name=e-commerce

### Conexion a base de datos H2 en memoria ###
# spring.datasource.url=jdbc:h2:mem:ecommerce_db
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

### Conexion a base de datos MySql ###
# Conexión database MySql Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/e-commerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=nahuel

### Configuracion de JPA ###
# Guardar cambios en reinicios de la aplicacion
spring.jpa.hibernate.ddl-auto=update
# Crear desde 0 la base de datos y las tablas
# spring.jpa.hibernate.ddl-auto=create

### Configuracion de Spring Security ###
jwt.secret=miClaveSecretaDe32CaracteresParaJWT2025
#24hs
jwt.expiration=86400000
